name: CD

permissions:
  contents: write

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g., v0.2.1)"
        required: true
        type: string

env:
  RUSTFLAGS: -D warnings --cfg tokio_unstable
  CARGO_TERM_COLOR: always

jobs:
  upload-assets:
    if: (startsWith(github.ref, 'refs/tags/klukai-v') || github.event.inputs.tag) && !contains(github.ref, '-types-') && !contains(github.ref, '-client-') && !contains(github.ref, '-agent-')
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v3

      - uses: rui314/setup-mold@v1

      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
        if: startsWith(matrix.os, 'ubuntu')

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: corrosion
          archive: "corrosion-$target"
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.tag && format('refs/tags/klukai-{0}', github.event.inputs.tag) || github.ref }}
